<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        Role::updateOrCreate(
            ['slug' => 'super_admin'],
            ['name' => 'Super Admin', 'type' => 'dashboard', 'is_system' => true]
        );

        Role::updateOrCreate(
            ['slug' => 'admin'],
            ['name' => 'Admin', 'type' => 'dashboard']
        );

        Role::updateOrCreate(
            ['slug' => 'user'],
            ['name' => 'User', 'type' => 'app', 'is_system' => true]
        );

        Role::updateOrCreate(
            ['slug' => 'driver'],
            ['name' => 'Driver', 'type' => 'app', 'is_system' => true]
        );

        // Tenant roles. `type = laundry` is what EnsureDashboardRole allows into
        // /admin and what keeps these out of the moderator role dropdown, which
        // filters on type = dashboard.
        $laundryOwner = Role::updateOrCreate(
            ['slug' => 'laundry_owner'],
            ['name' => 'Laundry Owner', 'type' => 'laundry', 'is_system' => true]
        );

        $laundryStaff = Role::updateOrCreate(
            ['slug' => 'laundry_staff'],
            ['name' => 'Laundry Staff', 'type' => 'laundry', 'is_system' => true]
        );

        // Permissions are generated by PermissionSeeder, so attach only what
        // already exists — order between the two seeders then does not matter.
        $this->syncPermissions($laundryOwner, [
            // Its own record only; the tenant scope guarantees "own".
            'laundry.view',
            'laundry.update',
            // Full control over its own staff.
            'laundry_staff.view',
            'laundry_staff.create',
            'laundry_staff.update',
            'laundry_staff.delete',
            'laundry_staff.toggle',
            // A laundry declares which services it offers — never their prices,
            // which are global and owned by the super admin. Note the absence of
            // any service.* / item.* / item_price.* permission here.
            'laundry_service.view',
            'laundry_service.update',
            // Same shape for territory: pick from the global zone list,
            // never create or rename a zone.
            'laundry_zone.view',
            'laundry_zone.update',
            // Its own orders only — the Order model's tenant scope does that, so
            // the permission is the whole of the gate here. No order.create: an
            // order is placed by a customer, never by the laundry.
            'order.view',
            'order.update',
            // The dispatch board. Not new power: an owner with `order.update`
            // can already assign a leg from the order page, and the board is
            // rooted in the tenant-scoped Order so it lists only its own. What
            // it removes is having to find those legs one order at a time —
            // and without it the queue on its own home page links to a 403.
            'order_task.view',
            // Revenue, orders and laundry performance only. `report.update` is
            // the super-admin gate for driver performance and operations health,
            // which are not tenant-scoped and would leak other laundries' drivers.
            'report.view',
            // Tenant-safe: OrderRating carries a laundry_id and uses
            // BelongsToLaundry, so an owner reads only its own verdicts.
            'order_rating.view',
            // What it is owed and what the platform took, order by order. Same
            // tenant guarantee: OrderSettlement uses BelongsToLaundry, so this
            // shows its own rows and no other laundry's. There is deliberately
            // no `.update` — a settlement is produced by an order completing and
            // is not something either party edits.
            //
            // Note this does NOT come with `wallet.view`, which is the right to
            // read every balance on the platform. An owner reads its own balance
            // through «محفظتي», which has no permission because it resolves the
            // wallet from the signed-in user.
            'order_settlement.view',
        ]);

        $this->syncPermissions($laundryStaff, [
            'laundry.view',
            'laundry_service.view',
            'laundry_zone.view',
            // Staff read orders; assigning one is the owner's call.
            'order.view',
        ]);

        /*
         * «مسؤول المندوبين» — the person who actually runs the couriers.
         *
         * Added because driver work had grown a queue of its own: papers a
         * driver has sent about their vehicle wait on somebody to check them,
         * and the notification is addressed to whoever holds
         * `driver_record_submission.update`. Without a role that ships with it,
         * that is nobody until an operator builds one by hand — and a queue
         * nobody is told about is a driver waiting on a screen that never moves.
         *
         * **Not `is_system`.** The structural roles are flagged so they cannot be
         * deleted; this one is a starting point an install is meant to adjust —
         * hand it the dispatch board or take it away, rename it, or delete it
         * entirely if one person does everything. Locking it would be asserting
         * we know how their operations desk is divided.
         */
        $driverSupervisor = Role::updateOrCreate(
            ['slug' => 'driver_supervisor'],
            ['name' => 'Driver Supervisor', 'type' => 'dashboard']
        );

        $this->syncPermissions($driverSupervisor, [
            // The couriers themselves: read them, create one after the call, keep
            // shifts and zones current, and suspend somebody who has stopped
            // turning up.
            'driver.view',
            'driver.create',
            'driver.update',
            'driver.toggle',

            // The queue this role exists for. `.update` is what the submitted
            // paperwork notification is addressed to.
            'driver_record_submission.view',
            'driver_record_submission.update',

            // Leads from «انضم لنا» — the same person rings them and creates the
            // driver, so splitting the two across roles would split one job.
            'driver_application.view',
            'driver_application.toggle',

            // The dispatch board. Reading it is not enough: handing a stranded
            // leg to somebody is the daily work of running couriers, and a
            // supervisor who has to fetch an admin to do it is not supervising.
            'order_task.view',
            'order_task.update',

            // Deliberately absent, and each for its own reason:
            //
            //   driver_earning.*, driver_bonus_rule.*, driver_bonus_award.*
            //     Money. The codebase gates every driver money term on
            //     `setting.update` precisely so the person managing a driver is
            //     not the person setting what that driver is paid.
            //
            //   order.*
            //     A driver supervisor needs the legs, not the customers' orders,
            //     their prices or their addresses beyond the stop itself.
            //
            //   user.*, report.update
            //     Neither is driver work, and both read far past it.
        ]);
    }

    /**
     * @param  array<int, string>  $slugs
     */
    protected function syncPermissions(Role $role, array $slugs): void
    {
        $ids = Permission::whereIn('slug', $slugs)->pluck('id')->all();

        $role->permissions()->sync($ids);
    }
}
