<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    public function run(): void
    {
        Role::updateOrCreate(
            ['slug' => 'super_admin'],
            ['name' => 'Super Admin', 'type' => 'dashboard', 'is_system' => true]
        );

        Role::updateOrCreate(
            ['slug' => 'admin'],
            ['name' => 'Admin', 'type' => 'dashboard']
        );

        Role::updateOrCreate(
            ['slug' => 'user'],
            ['name' => 'User', 'type' => 'app', 'is_system' => true]
        );

        Role::updateOrCreate(
            ['slug' => 'driver'],
            ['name' => 'Driver', 'type' => 'app', 'is_system' => true]
        );

        // Tenant roles. `type = laundry` is what EnsureDashboardRole allows into
        // /admin and what keeps these out of the moderator role dropdown, which
        // filters on type = dashboard.
        $laundryOwner = Role::updateOrCreate(
            ['slug' => 'laundry_owner'],
            ['name' => 'Laundry Owner', 'type' => 'laundry', 'is_system' => true]
        );

        $laundryStaff = Role::updateOrCreate(
            ['slug' => 'laundry_staff'],
            ['name' => 'Laundry Staff', 'type' => 'laundry', 'is_system' => true]
        );

        // Permissions are generated by PermissionSeeder, so attach only what
        // already exists — order between the two seeders then does not matter.
        $this->syncPermissions($laundryOwner, [
            // Its own record only; the tenant scope guarantees "own".
            'laundry.view',
            'laundry.update',
            // Full control over its own staff.
            'laundry_staff.view',
            'laundry_staff.create',
            'laundry_staff.update',
            'laundry_staff.delete',
            'laundry_staff.toggle',
            // A laundry declares which services it offers — never their prices,
            // which are global and owned by the super admin. Note the absence of
            // any service.* / item.* / item_price.* permission here.
            'laundry_service.view',
            'laundry_service.update',
            // Same shape for territory: pick from the global zone list,
            // never create or rename a zone.
            'laundry_zone.view',
            'laundry_zone.update',
            // Its own orders only — the Order model's tenant scope does that, so
            // the permission is the whole of the gate here. No order.create: an
            // order is placed by a customer, never by the laundry.
            'order.view',
            'order.update',
            // Revenue, orders and laundry performance only. `report.update` is
            // the super-admin gate for driver performance and operations health,
            // which are not tenant-scoped and would leak other laundries' drivers.
            'report.view',
            // Tenant-safe: OrderRating carries a laundry_id and uses
            // BelongsToLaundry, so an owner reads only its own verdicts.
            'order_rating.view',
        ]);

        $this->syncPermissions($laundryStaff, [
            'laundry.view',
            'laundry_service.view',
            'laundry_zone.view',
            // Staff read orders; assigning one is the owner's call.
            'order.view',
        ]);
    }

    /**
     * @param  array<int, string>  $slugs
     */
    protected function syncPermissions(Role $role, array $slugs): void
    {
        $ids = Permission::whereIn('slug', $slugs)->pluck('id')->all();

        $role->permissions()->sync($ids);
    }
}
