<?php

namespace App\Modules\Report\Models;

use App\Trait\DashboardModel;
use Illuminate\Database\Eloquent\Model;

/**
 * Not a table — the permission subject behind «ملخص الماليات».
 *
 * The same device `Report` and `LaundryRevenue` use: `PermissionGenerator`
 * derives slugs from the models in `config/dashboard.php`, so this exists only
 * so `finance.view` is generated by that machinery.
 *
 * It is its own permission, not `report.view`, because the point of the page is
 * who does **not** see it (the owner, 2026-09-30): the money used to sit on the
 * home page, which every panel account opens — moderators, a driver
 * supervisor, a laundry's staff. `report.view` is held by every laundry owner.
 * Nobody holds this one until somebody grants it; the super admin bypasses.
 */
class Finance extends Model
{
    use DashboardModel;

    /**
     * Nothing is ever read or written. Named only so a stray query fails loudly
     * rather than inventing a `finances` table.
     */
    protected $table = 'finances_do_not_exist';
}
