<?php

namespace App\Modules\Report\Models;

use App\Trait\DashboardModel;
use Illuminate\Database\Eloquent\Model;

/**
 * Not a table — a permission subject.
 *
 * `PermissionGenerator` walks `config/dashboard.php` and derives slugs from model
 * class names, which is how every other permission in this project comes to
 * exist. Reports need `report.view` and `report.update` and have nothing to store,
 * so this exists purely so they are generated by the same machinery as everything
 * else rather than hand-inserted somewhere nobody will find them.
 *
 * `report.view` gates the three tenant-scoped reports; `report.update` is used as
 * the super-admin gate for driver performance and operations health, which are not
 * scoped and would otherwise leak one tenant's drivers to another.
 */
class Report extends Model
{
    use DashboardModel;

    /**
     * Nothing is ever read or written. Named only so a stray query fails loudly
     * rather than inventing a `reports` table.
     */
    protected $table = 'reports_do_not_exist';
}
