<?php

use App\Models\ActivityLog;
use App\Models\Permission;
use App\Models\Role;
use App\Modules\Address\Models\Address;
use App\Modules\City\Models\City;
use App\Modules\Country\Models\Country;
use App\Modules\Coupon\Models\Coupon;
use App\Modules\Item\Models\Item;
use App\Modules\ItemCategory\Models\ItemCategory;
use App\Modules\Laundry\Models\Laundry;
use App\Modules\Notification\Models\DeviceToken;
use App\Modules\Notification\Models\NotificationLog;
use App\Modules\Offer\Models\Offer;
use App\Modules\Order\Models\OrderStatusLog;
use App\Modules\Payment\Models\OrderSettlementLine;
use App\Modules\Pricing\Models\PriceChangeItem;
use App\Modules\Service\Models\Service;
use App\Modules\TimeSlot\Models\TimeSlot;
use App\Modules\User\Models\User;
use App\Modules\Zone\Models\Zone;
use Illuminate\Notifications\DatabaseNotification;
use Laravel\Sanctum\PersonalAccessToken;

/*
|--------------------------------------------------------------------------
| The activity log — who changed what
|--------------------------------------------------------------------------
|
| Every model created, updated or deleted is recorded by
| App\Services\ActivityLogger: who, from where (the panel, an app, the system),
| through which route, and each field before and after. These lists are what
| it leaves out, and each entry is a decision rather than a default.
|
*/

return [

    // A switch for an emergency, not a setting: off means changes go unrecorded.
    'enabled' => (bool) env('ACTIVITY_LOG_ENABLED', true),

    // How long a row is kept before `laundo:prune` removes it — six months,
    // the owner's call. `order_status_logs` is separate and never pruned: the
    // customer app's tracking screen is built from it.
    'retention_days' => (int) env('ACTIVITY_RETENTION_DAYS', 183),

    // Models not recorded at all. Each is either a log of its own, a delivery
    // artefact, or a row derived from another that is recorded already.
    'excluded' => [
        ActivityLog::class,
        NotificationLog::class,
        DeviceToken::class,
        DatabaseNotification::class,
        PersonalAccessToken::class,
        // Written in bulk under a PriceChange, which is itself recorded.
        PriceChangeItem::class,
        // Rewritten on every settlement recompute; the settlement is recorded.
        OrderSettlementLine::class,
        // A log of its own — every order status with its actor — which the
        // order's history reads directly.
        OrderStatusLog::class,
        // Generated by PermissionSeeder on deploy, never by a person: a
        // screenful of «System added activity_log.toggle» after every release
        // buried the changes somebody actually made.
        Permission::class,
    ],

    // Attributes whose change alone is not worth a row. The driver reports a
    // position every few seconds; recording each would bury everything else.
    // An OTP sent, or the remember-me token cycled at every sign-in and
    // sign-out, is not a change anybody made to an account — the sign-in is
    // its own row.
    'ignored_attributes' => [
        'created_at', 'updated_at',
        'last_lat', 'last_lng', 'located_at',
        'last_used_at',
        'otp', 'otp_expires_at', 'otp_attempts',
        'remember_token',
    ],

    // Attributes recorded as «changed» without their value. Matched against the
    // attribute name, case-insensitively, as a substring.
    'redacted' => [
        'password', 'remember_token', 'token', 'secret', 'otp', 'payload', 'api_key',
    ],

    // Setting rows whose value is a credential. A setting stores its value in
    // one column, so the key decides.
    'redacted_setting_keys' => [
        'Google_Maps_Key',
    ],

    /*
    | How the screens word a row — for the owner, not for us. Everything below
    | is display only: what is recorded does not change.
    */

    // Fields that are recorded but never shown: they mean nothing to the
    // person reading the log. Exact names, then name endings.
    'hidden_fields' => [
        'id', 'slug', 'guard_name', 'order_id', 'sequence',
        'created_at', 'updated_at', 'deleted_at',
        'lat', 'lng', 'latitude', 'longitude',
        // A piece count difference: whether it is open is what its review's
        // own fields say.
        'open',
        // A zone's drawing is a list of corners — noise in a sentence. The row
        // still says the zone was edited; its box columns end in _lat/_lng.
        'boundary',
    ],
    'hidden_suffixes' => ['_lat', '_lng', '_token'],

    // Columns holding another record's id, shown by that record's name.
    'references' => [
        'item_id' => Item::class,
        'item_category_id' => ItemCategory::class,
        'service_id' => Service::class,
        'laundry_id' => Laundry::class,
        'city_id' => City::class,
        'country_id' => Country::class,
        'zone_id' => Zone::class,
        'role_id' => Role::class,
        'coupon_id' => Coupon::class,
        'offer_id' => Offer::class,
        'pickup_slot_id' => TimeSlot::class,
        'delivery_slot_id' => TimeSlot::class,
        'time_slot_id' => TimeSlot::class,
        'pickup_address_id' => Address::class,
        'delivery_address_id' => Address::class,
        'address_id' => Address::class,
        'user_id' => User::class,
        'driver_id' => User::class,
        'answered_by' => User::class,
        'applied_by' => User::class,
        'approved_by' => User::class,
        'created_by' => User::class,
        'handled_by' => User::class,
        'requested_by' => User::class,
        'reversed_by' => User::class,
        'reviewed_by' => User::class,
        'counted_by' => User::class,
        'resolved_by' => User::class,
        'sent_by' => User::class,
        'undone_by' => User::class,
        'uploaded_by' => User::class,
    ],

    // What each kind of record is called, one of it: «Changed a city».
    // Translated through ar.json; a model missing here reads by its class name.
    'nouns' => [
        'Address' => 'Address',
        'banner' => 'Banner',
        'City' => 'City',
        'CommissionRule' => 'Laundry share',
        'Complaint' => 'Complaint',
        'ComplaintAttachment' => 'Complaint attachment',
        'Country' => 'Country',
        'Coupon' => 'Coupon',
        'CouponRedemption' => 'Coupon use',
        'Driver' => 'Driver',
        'DriverApplication' => 'Driver application',
        'DriverBonusAward' => 'Driver bonus',
        'DriverBonusRule' => 'Driver bonus rule',
        'DriverBonusTier' => 'Bonus tier',
        'DriverEarning' => 'Driver earning',
        'DriverProfile' => 'Driver details',
        'DriverRecordSubmission' => 'Driver details change',
        'Faq' => 'FAQ',
        'intro' => 'Intro screen',
        'Item' => 'Item',
        'ItemCategory' => 'Item category',
        'ItemPrice' => 'Price',
        'JourneyStep' => 'Journey step',
        'Language' => 'Language',
        'Laundry' => 'Laundry',
        'LaundryDeduction' => 'Laundry deduction',
        'LaundryRevenue' => 'Laundry revenue',
        'LaundryService' => 'Laundry service',
        'LaundryServiceRequest' => 'Laundry service request',
        'LaundrySlotCapacity' => 'Laundry capacity',
        'LaundryStaff' => 'Laundry staff member',
        'LaundryZone' => 'Laundry zone',
        'Moderator' => 'Moderator',
        'NotificationPreference' => 'Notification setting',
        'Offer' => 'Offer',
        'Order' => 'Order',
        'OrderItem' => 'Piece',
        'OrderMedia' => 'Order photo',
        'OrderPriceQuery' => 'Price query',
        'OrderRating' => 'Rating',
        'OrderRecurrence' => 'Recurring order',
        'OrderSettlement' => 'Settlement',
        'OrderTask' => 'Driver trip',
        'PieceDiscrepancy' => 'Piece count difference',
        'Payment' => 'Payment',
        'PriceChange' => 'Price increase',
        'RecurrencePrompt' => 'Recurring order reminder',
        'Refund' => 'Refund',
        'Role' => 'Role',
        'Service' => 'Service',
        'Setting' => 'Setting',
        'TimeSlot' => 'Time slot',
        'User' => 'Account',
        'Wallet' => 'Wallet',
        'WalletTransaction' => 'Wallet transaction',
        'Zone' => 'Zone',
    ],

    // Who somebody was, by their role. A role added later reads by its name.
    'roles' => [
        'super_admin' => 'Platform manager',
        'admin' => 'Admin',
        'user' => 'Customer',
        'driver' => 'Driver',
        'laundry_owner' => 'Laundry owner',
        'laundry_staff' => 'Laundry staff',
        'driver_supervisor' => 'Driver supervisor',
    ],
];
