<?php

namespace Laundo\SecondBrain\Export;

use Laundo\SecondBrain\Brain;
use Laundo\SecondBrain\Support\Json;

/**
 * A picture of the graph, for people rather than for tools.
 *
 * Deliberately small. The searchable brain is the product; a diagram is a
 * convenience, and one that tried to draw 5,500 nodes would be a grey rectangle.
 * So the export is at **community and module granularity** — the level somebody
 * is actually asking about when they open a diagram — and the HTML view lets
 * them drill from there into the module detail the JSON already holds.
 */
final class Exporter
{
    public function __construct(private readonly Brain $brain) {}

    /**
     * @return list<string>  paths written, repo-relative
     */
    public function export(string $format = 'all'): array
    {
        $written = [];

        if ($format === 'all' || $format === 'mermaid') {
            $written[] = $this->write('export/architecture.mmd', $this->mermaid());
        }

        if ($format === 'all' || $format === 'json') {
            $written[] = $this->write('export/graph-summary.json', json_encode(
                $this->summary(),
                Json::WRITE_FLAGS
            ) ?: '{}');
        }

        if ($format === 'all' || $format === 'html') {
            $written[] = $this->write('export/architecture.html', $this->html());
        }

        // The interactive viewer's payload. Produced by `export` as well as by
        // `visualize`, so the picture cannot silently lag the graph it is drawn
        // from — anybody who exports gets a current one.
        if ($format === 'all' || $format === 'viewer') {
            $viewer = (new ViewerData($this->brain))->write();
            $written[] = $viewer['json'];
            $written[] = $viewer['js'];
        }

        return $written;
    }

    private function write(string $relative, string $contents): string
    {
        $path = $this->brain->paths()->data($relative);
        $directory = dirname($path);

        if (! is_dir($directory)) {
            mkdir($directory, 0777, true);
        }

        file_put_contents($path, $contents);

        return $this->brain->paths()->relative($path);
    }

    public function mermaid(): string
    {
        $communities = $this->brain->architecture('communities')['communities'];
        $dependencies = Json::read($this->brain->paths()->data('graph/dependencies.json'), []);

        $lines = [
            '%% Laundo — communities and the modules inside them.',
            '%% Generated by .second-brain; edit the code, not this file.',
            'graph LR',
        ];

        $moduleToCommunity = [];

        foreach ($communities as $community) {
            if ($community['modules'] === []) {
                continue;
            }

            $lines[] = '  subgraph '.$this->id($community['slug']).'["'.$this->label($community['title']).'"]';
            foreach ($community['modules'] as $module) {
                $moduleToCommunity[$module] ??= $community['slug'];
                if ($moduleToCommunity[$module] !== $community['slug']) {
                    continue;   // a module is drawn once, in its primary home
                }
                $lines[] = '    '.$this->id($module).'["'.$this->label($module).'"]';
            }
            $lines[] = '  end';
        }

        // Only the heavier couplings. Every cross-module edge would be a
        // hairball and the point of the picture is which ones are load-bearing.
        $drawn = [];
        foreach ($dependencies as $module => $detail) {
            foreach ($detail['depends_on'] as $target => $weight) {
                if ($weight < 4 || isset($drawn[$target.'|'.$module])) {
                    continue;
                }
                if (! isset($moduleToCommunity[$module], $moduleToCommunity[$target])) {
                    continue;
                }
                $drawn[$module.'|'.$target] = true;
                $lines[] = '  '.$this->id($module).' --> '.$this->id($target);
            }
        }

        return implode("\n", $lines)."\n";
    }

    /** @return array<string,mixed> */
    public function summary(): array
    {
        $manifest = $this->brain->manifest();
        $communities = $this->brain->architecture('communities')['communities'];

        return [
            'generated_at' => $manifest['built_at'] ?? null,
            'totals' => [
                'nodes' => $manifest['nodes'] ?? 0,
                'edges' => $manifest['edges'] ?? 0,
                'communities' => $manifest['communities'] ?? 0,
                'modules' => $manifest['modules'] ?? 0,
                'features' => $manifest['features'] ?? 0,
                'routes' => $manifest['routes'] ?? 0,
                'tables' => $manifest['tables'] ?? 0,
            ],
            'communities' => array_map(static fn (array $c) => [
                'slug' => $c['slug'],
                'title' => $c['title'],
                'source' => $c['source'],
                'evidence' => $c['evidence'],
                'modules' => $c['modules'],
                'inferred_modules' => $c['inferred_modules'] ?? [],
                'tables' => $c['tables'],
                'routes' => $c['route_count'],
                'nodes' => $c['node_count'],
                'cohesion' => $c['cohesion'],
            ], $communities),
        ];
    }

    private function html(): string
    {
        $summary = $this->summary();
        $modules = Json::read($this->brain->paths()->data('architecture/modules.json'), []);

        // Escaped like every other value interpolated into this page. The
        // source is repo-controlled today, which is a reason it has not bitten
        // and not a reason to leave it — a module named with an angle bracket
        // would break the document.
        $mermaid = htmlspecialchars($this->mermaid(), ENT_QUOTES | ENT_SUBSTITUTE);

        $rows = '';
        foreach ($summary['communities'] as $community) {
            $inferred = $community['inferred_modules'] === []
                ? ''
                : ' <span class="inferred">+'.htmlspecialchars(implode(', ', $community['inferred_modules']), ENT_QUOTES).' (inferred)</span>';

            $rows .= '<tr>'
                .'<td><strong>'.htmlspecialchars($community['title'], ENT_QUOTES).'</strong><br><code>'.htmlspecialchars($community['slug'], ENT_QUOTES).'</code></td>'
                .'<td><span class="src src-'.htmlspecialchars($community['source'], ENT_QUOTES).'">'.htmlspecialchars($community['source'], ENT_QUOTES).'</span><br><small>'.htmlspecialchars($community['evidence'], ENT_QUOTES).'</small></td>'
                .'<td>'.htmlspecialchars(implode(', ', $community['modules']), ENT_QUOTES).$inferred.'</td>'
                .'<td class="num">'.$community['routes'].'</td>'
                .'<td class="num">'.$community['nodes'].'</td>'
                .'<td class="num">'.number_format($community['cohesion'], 2).'</td>'
                .'</tr>';
        }

        $moduleRows = '';
        foreach ($modules as $module) {
            $moduleRows .= '<tr>'
                .'<td><strong>'.htmlspecialchars($module['name'], ENT_QUOTES).'</strong></td>'
                .'<td>'.htmlspecialchars((string) $module['community'], ENT_QUOTES).'</td>'
                .'<td class="num">'.$module['files'].'</td>'
                .'<td>'.htmlspecialchars(implode(', ', array_keys($module['layers'])), ENT_QUOTES).'</td>'
                .'<td>'.htmlspecialchars(implode(', ', array_slice($module['owns_tables'], 0, 8)), ENT_QUOTES).'</td>'
                .'<td class="summary">'.htmlspecialchars(mb_substr($module['summary'], 0, 140), ENT_QUOTES).'</td>'
                .'</tr>';
        }

        $totals = $summary['totals'];
        $generated = htmlspecialchars((string) $summary['generated_at'], ENT_QUOTES);

        return <<<HTML
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Laundo — architecture map</title>
<style>
  :root { color-scheme: light dark; --ink:#12181f; --muted:#5b6672; --line:#e2e6ea; --bg:#fbfcfd; --accent:#2b6cb0; }
  @media (prefers-color-scheme: dark) { :root { --ink:#e6edf3; --muted:#9aa7b2; --line:#2a323c; --bg:#0f1419; --accent:#7ab8f5; } }
  * { box-sizing: border-box; }
  body { margin:0; padding:2rem 1rem 4rem; font:15px/1.55 ui-sans-serif,system-ui,"Segoe UI",sans-serif; color:var(--ink); background:var(--bg); }
  main { max-width: 1100px; margin-inline: auto; }
  h1 { font-size:1.6rem; margin:0 0 .25rem; }
  h2 { font-size:1.1rem; margin:2.5rem 0 .75rem; border-bottom:1px solid var(--line); padding-bottom:.4rem; }
  p.lede { color:var(--muted); margin:0 0 1.5rem; }
  .stats { display:flex; flex-wrap:wrap; gap:.75rem; margin-bottom:1rem; }
  .stat { border:1px solid var(--line); border-radius:8px; padding:.6rem .9rem; min-width:100px; }
  .stat b { display:block; font-size:1.35rem; }
  .stat span { color:var(--muted); font-size:.78rem; text-transform:uppercase; letter-spacing:.04em; }
  table { width:100%; border-collapse:collapse; font-size:.87rem; }
  th,td { text-align:start; padding:.5rem .6rem; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--muted); font-weight:600; font-size:.74rem; text-transform:uppercase; letter-spacing:.04em; }
  td.num { text-align:end; font-variant-numeric:tabular-nums; }
  td.summary { color:var(--muted); }
  code { font:0.8em ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--accent); }
  small { color:var(--muted); }
  .src { display:inline-block; font-size:.7rem; padding:.1rem .4rem; border-radius:4px; border:1px solid var(--line); }
  .src-menu { border-color:var(--accent); color:var(--accent); }
  .inferred { color:var(--muted); font-size:.8em; }
  pre.mermaid { overflow-x:auto; border:1px solid var(--line); border-radius:8px; padding:1rem; background:transparent; }
  .wrap { overflow-x:auto; }
</style>
</head>
<body>
<main>
  <h1>Laundo — architecture map</h1>
  <p class="lede">Generated from the source by <code>.second-brain</code> on {$generated}. Do not edit; rebuild it.</p>

  <div class="stats">
    <div class="stat"><b>{$totals['communities']}</b><span>communities</span></div>
    <div class="stat"><b>{$totals['modules']}</b><span>modules</span></div>
    <div class="stat"><b>{$totals['features']}</b><span>features</span></div>
    <div class="stat"><b>{$totals['routes']}</b><span>routes</span></div>
    <div class="stat"><b>{$totals['tables']}</b><span>tables</span></div>
    <div class="stat"><b>{$totals['nodes']}</b><span>nodes</span></div>
    <div class="stat"><b>{$totals['edges']}</b><span>edges</span></div>
  </div>

  <h2>Communities</h2>
  <p class="lede"><code>menu</code> means the grouping came from <code>config/menu.php</code>, which the owner arranged. <code>derived</code> means the directory layout. Cohesion is internal edges over all edges touching the community — low is not a fault, it means changes here reach outside.</p>
  <div class="wrap">
  <table>
    <thead><tr><th>Community</th><th>Source</th><th>Modules</th><th>Routes</th><th>Nodes</th><th>Cohesion</th></tr></thead>
    <tbody>{$rows}</tbody>
  </table>
  </div>

  <h2>Modules</h2>
  <div class="wrap">
  <table>
    <thead><tr><th>Module</th><th>Community</th><th>Files</th><th>Layers</th><th>Owns tables</th><th>What it is</th></tr></thead>
    <tbody>{$moduleRows}</tbody>
  </table>
  </div>

  <h2>Module dependencies</h2>
  <p class="lede">Arrows are cross-module dependencies with a weight of four or more. Renders as a diagram wherever Mermaid is available; the source is readable either way.</p>
  <pre class="mermaid">{$mermaid}</pre>
</main>
</body>
</html>

HTML;
    }

    private function id(string $name): string
    {
        return preg_replace('/[^A-Za-z0-9_]/', '_', $name) ?? 'n';
    }

    private function label(string $text): string
    {
        return str_replace(['"', '[', ']'], ['', '(', ')'], $text);
    }
}
